# --- Stage 1: Build & Dependencies ---
# Using the official lightweight alpine image to keep the image footprint small
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application files
COPY . .

# Run tests to ensure everything is working before building the final image
RUN npm test

# Keep only production dependencies for the final image
RUN npm ci --omit=dev


# ---------------------------------------------------------------------------------------


# --- Stage 2: Final Runner (final production image)---
# Using the same alpine image for the runner to maintain consistency
FROM node:20-alpine AS runner

# Set Enviroment to produciton to ensure we only install production dependencies
ENV NODE_ENV=production
WORKDIR /app

# Create a non-root user to run the application for security reasons
RUN addgroup -g 1001 -S nodejs && \
    adduser -u 1001 -S nodejs -G nodejs

# Copy only the necessary files from the builder stage to keep the final image clean
COPY --from=builder --chown=nodejs:nodejs /app/package*.json ./
COPY --from=builder --chown=nodejs:nodejs /app/server.js ./server.js
COPY --from=builder --chown=nodejs:nodejs /app/node_modules ./node_modules


# Switch to the non-root user
USER nodejs

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["node", "server.js"]
